name: Pull reqests tests

on: pull_request

jobs:
  PR_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: sudo apt update && sudo apt install -y g++ make cmake build-essential

      - name: Compile the tests
        run: |
          cmake ./CMakeLists.txt
          make

      - name: Run tests
        run: |
            ctest --output-on-failure